

import type { Metadata } from "next";

import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";

import ButtonBehavior from "@/components/ButtonBehavior";
import ScrollToTopButton from "@/components/ScrollTopButton";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Rumpke Inmobilien",
  description: "Generated by Rumpke Inmobilien",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {/* <TitleScroller /> */}
        <ButtonBehavior />
        <ScrollToTopButton />
      </body>
    </html>
  );
}
