

import type { Metadata } from "next";

import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";


import Header from "@/header/components/Header";
import { ThemeProvider } from "@/context/ThemeContext";
import Footer from "@/components/Footer";
import KeywordCarousel from "@/header/components/KeywordCarousel";
import QuickLinksBar from "@/components/quick-links-bar/QuickLinksBar";
import MoreInfo from "@/components/MoreInfo";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Rumpke Inmobilien",
  description: "Generated by Rumpke Inmobilien",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <div className=" w-full text-gray-800 dark:text-gray-300 mx-auto bg-white dark:bg-gray-950">
            <div className="2xl:w-[85%] dark:bg-dark-300  mx-auto shadow-[0px_-12px_12px_5px_rgba(0,0,0,0.12)] dark:shadow-[0px_-12px_12px_2px_rgba(0,255,180,0.10)]">
              <KeywordCarousel />
            <Header />
            {children}
            <QuickLinksBar />
            <MoreInfo/>
            <Footer />
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
