

import type { Metadata } from "next";

import "./globals.css";
import { mainFont, titleFonts } from "@/config/fonts";
import Header from "@/components/header/components/Header";
import { ThemeProvider } from "@/context/ThemeContext";
import Footer from "@/components/Footer";
import KeywordCarousel from "@/components/header/components/KeywordCarousel";
import QuickLinksBar from "@/components/quick-links-bar/QuickLinksBar";
import { RainbowProvider } from "@/hooks/useRainBow";
import CookieConsentClient from "@/components/cookie/CookieConsentClient";
import { AIChatProvider } from "@/context/AIChatContext";
import MainTitle from "@/components/MainTitle";







export const metadata: Metadata = {
  title: "Ich schenke dir was",
  description: "Generated by Rumpke Inmobilien",
  openGraph: {
    title: "Ich schenke dir was",
    description: "Generated by Rumpke Immobilien",
    url: "https://www.ichschenkedirwas.de/",
    siteName: "Ich schenke dir was",
    images: [
      {
        url: "https://www.ichschenkedirwas.de/hero-pic-2.jpg",
        width: 1200,
        height: 630,
        alt: "Ich schenke dir was",
      },
    ],
    locale: "de_DE",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Ich schenke dir was",
    description: "Generated by Rumpke Inmobilien",
    images: ["https://www.ichschenkedirwas.de/hero-pic-2.jpg"],
  },
};

export default function RootLayout({


  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="de">
      <head>
        <meta property="og:title" content="Ich schenke dir was" />
        <meta property="og:description" content="Generated by Rumpke Immobilien" />
        <meta property="og:url" content="https://www.ichschenkedirwas.de/" />
        <meta property="og:site_name" content="Ich schenke dir was" />
        <meta property="og:image" content="https://www.ichschenkedirwas.de/hero-pic-2.jpg" />
        <meta property="og:image:width" content="1200" />
        <meta property="og:image:height" content="630" />
        <meta property="og:locale" content="de_DE" />
        <meta property="og:type" content="website" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Ich schenke dir was" />
        <meta name="twitter:description" content="Generated by Rumpke Inmobilien" />
        <meta name="twitter:image" content="https://www.ichschenkedirwas.de/hero-pic-2.jpg" />
      </head>
      <body
        className={`${mainFont.variable} antialiased`}
      >
        <ThemeProvider>
          <AIChatProvider>
            <div className="duration-100 w-full text-gray-800 dark:text-gray-300 mx-auto bg-light-100 dark:bg-black font-sans">
              <KeywordCarousel />
              <div className="duration-100 bg-white 2xl:w-[85%] dark:bg-dark-300 mx-auto">
                <div className="dark:shadow-subtle-d shadow-subtle-l">
                  <RainbowProvider>
                    <Header />
                    {children}
                  </RainbowProvider>
                  <div className="bg-mint-600 dark:bg-mint-700 duration-100 text-white">
                    <QuickLinksBar />
                    <Footer />
                    <MainTitle />
                  </div>
                </div>
              </div>
            </div>
            <CookieConsentClient />
          </AIChatProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
